apiVersion: v1
kind: ConfigMap
metadata:
  name: prophet-forecaster-config
  namespace: sre
data:
  config.yaml: |
    prometheus:
      url: "https://prometheus.sitopflab03.otv-staging.com"

    data:
      use_historical: false
      lookback_days: 14

    metrics:
      - name: "memory_elasticsearch01_used"
        query: 'sum(node_memory_MemTotal_bytes{instance="elasticsearch01", job="elasticsearch-nodes"} - node_memory_MemAvailable_bytes{instance="elasticsearch01", job="elasticsearch-nodes"})'
        forecast_periods: 60
        seasonality: "daily"

      - name: "cpu_elasticsearch01_used"
        query: 'avg by (instance) (rate(node_cpu_seconds_total{mode!="idle", instance="elasticsearch01", job="elasticsearch-nodes"}[5m])) * 100'
        forecast_periods: 60
        seasonality: "daily"

      - name: "disk_elasticsearch01_used"
        query: '1 - (sum(elasticsearch_filesystem_data_available_bytes{host="elasticsearch01"})/sum(elasticsearch_filesystem_data_size_bytes{host="elasticsearch01"}))'
        forecast_periods: 60
        seasonality: "daily"
      