apiVersion: v1
kind: Service
metadata:
  name: historical-forecaster
  namespace: sre
spec:
  selector:
    app: historical-forecaster
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
