apiVersion: v1
kind: Service
metadata:
  name: prophet-forecaster
  namespace: sre
  labels:
    app: prophet-forecaster
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: prophet-forecaster
