apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourier-anomaly-detector
  namespace: sre
  labels:
    app: fourier-anomaly-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fourier-anomaly-detector
  template:
    metadata:
      labels:
        app: fourier-anomaly-detector
    spec:
      containers:
        - name: prometheus-anomaly-detector
          image: sohamsal2026/fourier-historical:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
          env:
            - name: FLT_PROM_URL
              # Update this to exactly match your Prometheus cluster URL address
              value: "https://prometheus.sitopflab03.otv-staging.com" 
            - name: FLT_PROM_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prometheus-auth
                  key: token
            - name: FLT_TARGET_QUERY
              value: "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{app='ingress-gateway-otvpcse',request_url='/ias/v1/contentlicenses/widevine'}[10m])) by (le))"
            - name: FLT_REGRESSOR_CPU
              value: "sum(rate(container_cpu_usage_seconds_total{namespace='otvpcse', pod=~'ias-.*', container!='POD'}[10m]))"
            - name: FLT_REGRESSOR_RPS
              value: "sum(rate(istio_requests_total{app='ingress-gateway-otvpcse',request_url='/ias/v1/contentlicenses/widevine'}[10m]))"
            - name: FLT_REGRESSOR_5XX
              value: "sum(rate(istio_requests_total{app='ingress-gateway-otvpcse', response_code=~'5.*', request_url='/ias/v1/contentlicenses/widevine'}[10m]))"
            - name: FLT_DATA_START_TIME
              value: "2026-02-16T12:00:00Z"
            - name: FLT_DATA_END_TIME
              value: "2026-03-04T05:21:16Z"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"