apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourier-postgres
  namespace: sre
  labels:
    app: fourier-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fourier-postgres
  template:
    metadata:
      labels:
        app: fourier-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: fourier_user
        - name: POSTGRES_PASSWORD
          value: fourier_pass
        - name: POSTGRES_DB
          value: fourier_db
---
apiVersion: v1
kind: Service
metadata:
  name: fourier-postgres-service
  namespace: sre
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: fourier-postgres
